### ISSUE TITLE
Error when trying to access login / signup page on OpenID Connect Implicit Flow Demo

### ISSUE THREAD

**Issue by patricknolan** [openiddict/openiddict-samples#50]
Hi,

I have followed the instructions [here](https://github.com/openiddict/openiddict-samples/tree/master/samples/ImplicitFlow) but get the following error when I click on the "login / signup" link.

vendor-bundle.js:14283 ERROR [app-router] Error: Network Error
    at XMLHttpRequest.s.onerror (http://localhost:9000/scripts/vendor-bundle.js:26246:27086)
From previous event:
    at t.getJson (http://localhost:9000/scripts/vendor-bundle.js:26246:26794)
    at t.getMetadata (http://localhost:9000/scripts/vendor-bundle.js:26246:23437)
    at t._getMetadataProperty (http://localhost:9000/scripts/vendor-bundle.js:26246:24956)
    at t.getAuthorizationEndpoint (http://localhost:9000/scripts/vendor-bundle.js:26246:23943)
    at e.t.createSigninRequest (http://localhost:9000/scripts/vendor-bundle.js:26246:4308)
    at http://localhost:9000/scripts/vendor-bundle.js:26319:11990
    at <anonymous>
From previous event:
    at e._signinStart (http://localhost:9000/scripts/vendor-bundle.js:26319:11917)
    at e.signinRedirect (http://localhost:9000/scripts/vendor-bundle.js:26319:9960)
    at OpenIdConnectNavigationStrategies.login (http://localhost:9000/scripts/app-bundle.js:540:37)
    at Object.navigationStrategy (http://localhost:9000/scripts/app-bundle.js:382:68)
    at evaluateNavigationStrategy (http://localhost:9000/scripts/debug-bundle.js:1135:38)
    at AppRouter._createNavigationInstruction (http://localhost:9000/scripts/debug-bundle.js:1068:18)
    at AppRouter.loadUrl (http://localhost:9000/scripts/debug-bundle.js:1676:19)
    at BrowserHistory._loadUrl (http://localhost:9000/scripts/vendor-bundle.js:13611:55)
    at BrowserHistory.navigate (http://localhost:9000/scripts/vendor-bundle.js:13567:21)
    at HTMLDocument.DefaultLinkHandler._this.handler (http://localhost:9000/scripts/vendor-bundle.js:13378:25)
error @ vendor-bundle.js:14283
(anonymous) @ vendor-bundle.js:13878
(anonymous) @ debug-bundle.js:1679
tryCatcher @ vendor-bundle.js:3411
Promise._settlePromiseFromHandler @ vendor-bundle.js:2627
Promise._settlePromise @ vendor-bundle.js:2684
Promise._settlePromise0 @ vendor-bundle.js:2729
Promise._settlePromises @ vendor-bundle.js:2804
(anonymous) @ vendor-bundle.js:153

**When I run the RunDemo.ps1 I also get these errors in the aurelia console**
node_modules\@types\whatwg-fetch\index.d.ts(11,13): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(11,13): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
node_modules\@types\whatwg-fetch\index.d.ts(13,14): error TS2300: Duplicate identifier 'HeadersInit'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(13,14): error TS2300: Duplicate identifier 'HeadersInit'.
node_modules\@types\whatwg-fetch\index.d.ts(14,15): error TS2300: Duplicate identifier 'Headers'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(14,15): error TS2300: Duplicate identifier 'Headers'.
node_modules\@types\whatwg-fetch\index.d.ts(31,14): error TS2300: Duplicate identifier 'BodyInit'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(31,14): error TS2300: Duplicate identifier 'BodyInit'.
node_modules\@types\whatwg-fetch\index.d.ts(43,14): error TS2300: Duplicate identifier 'RequestInfo'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(43,14): error TS2300: Duplicate identifier 'RequestInfo'.
node_modules\@types\whatwg-fetch\index.d.ts(44,15): error TS2300: Duplicate identifier 'Request'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(44,15): error TS2300: Duplicate identifier 'Request'.
node_modules\@types\whatwg-fetch\index.d.ts(64,11): error TS2300: Duplicate identifier 'Request'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(64,11): error TS2300: Duplicate identifier 'Request'.
node_modules\@types\whatwg-fetch\index.d.ts(76,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'window' must be of type 'any', but here has type 'null'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(76,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'window' must be of type 'any', but here has type 'null'.
node_modules\@types\whatwg-fetch\index.d.ts(79,6): error TS2300: Duplicate identifier 'RequestType'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(79,6): error TS2300: Duplicate identifier 'RequestType'.
node_modules\@types\whatwg-fetch\index.d.ts(80,6): error TS2300: Duplicate identifier 'RequestDestination'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(80,6): error TS2300: Duplicate identifier 'RequestDestination'.
node_modules\@types\whatwg-fetch\index.d.ts(81,6): error TS2300: Duplicate identifier 'RequestMode'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(81,6): error TS2300: Duplicate identifier 'RequestMode'.
node_modules\@types\whatwg-fetch\index.d.ts(82,6): error TS2300: Duplicate identifier 'RequestCredentials'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(82,6): error TS2300: Duplicate identifier 'RequestCredentials'.
node_modules\@types\whatwg-fetch\index.d.ts(83,6): error TS2300: Duplicate identifier 'RequestCache'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(83,6): error TS2300: Duplicate identifier 'RequestCache'.
node_modules\@types\whatwg-fetch\index.d.ts(84,6): error TS2300: Duplicate identifier 'RequestRedirect'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(84,6): error TS2300: Duplicate identifier 'RequestRedirect'.
node_modules\@types\whatwg-fetch\index.d.ts(86,6): error TS2300: Duplicate identifier 'ReferrerPolicy'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(86,6): error TS2300: Duplicate identifier 'ReferrerPolicy'.
node_modules\@types\whatwg-fetch\index.d.ts(88,15): error TS2300: Duplicate identifier 'Response'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(88,15): error TS2300: Duplicate identifier 'Response'.
node_modules\@types\whatwg-fetch\index.d.ts(107,11): error TS2300: Duplicate identifier 'Response'.
[20:47:06] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(107,11): error TS2300: Duplicate identifier 'Response'.
node_modules\@types\whatwg-fetch\index.d.ts(115,6): error TS2300: Duplicate identifier 'ResponseType'.
[20:47:07] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-fetch\index.d.ts(115,6): error TS2300: Duplicate identifier 'ResponseType'.
node_modules\@types\whatwg-streams\index.d.ts(32,15): error TS2300: Duplicate identifier 'ReadableStream'.
[20:47:07] gulp-notify: [Error running Gulp] Error: node_modules\@types\whatwg-streams\index.d.ts(32,15): error TS2300: Duplicate identifier 'ReadableStream'.
__lib/lib.dom.d.ts(3896,11): error TS2300: Duplicate identifier 'Headers'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(3896,11): error TS2300: Duplicate identifier 'Headers'.
__lib/lib.dom.d.ts(3905,13): error TS2300: Duplicate identifier 'Headers'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(3905,13): error TS2300: Duplicate identifier 'Headers'.
__lib/lib.dom.d.ts(9029,11): error TS2300: Duplicate identifier 'ReadableStream'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9029,11): error TS2300: Duplicate identifier 'ReadableStream'.
__lib/lib.dom.d.ts(9035,13): error TS2300: Duplicate identifier 'ReadableStream'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9035,13): error TS2300: Duplicate identifier 'ReadableStream'.
__lib/lib.dom.d.ts(9051,11): error TS2300: Duplicate identifier 'Request'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9051,11): error TS2300: Duplicate identifier 'Request'.
__lib/lib.dom.d.ts(9068,13): error TS2300: Duplicate identifier 'Request'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9068,13): error TS2300: Duplicate identifier 'Request'.
__lib/lib.dom.d.ts(9073,11): error TS2300: Duplicate identifier 'Response'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9073,11): error TS2300: Duplicate identifier 'Response'.
__lib/lib.dom.d.ts(9084,13): error TS2300: Duplicate identifier 'Response'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(9084,13): error TS2300: Duplicate identifier 'Response'.
__lib/lib.dom.d.ts(14687,18): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14687,18): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
__lib/lib.dom.d.ts(14692,6): error TS2300: Duplicate identifier 'BodyInit'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14692,6): error TS2300: Duplicate identifier 'BodyInit'.
__lib/lib.dom.d.ts(14713,6): error TS2300: Duplicate identifier 'HeadersInit'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14713,6): error TS2300: Duplicate identifier 'HeadersInit'.
__lib/lib.dom.d.ts(14723,6): error TS2300: Duplicate identifier 'RequestInfo'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14723,6): error TS2300: Duplicate identifier 'RequestInfo'.
__lib/lib.dom.d.ts(14771,6): error TS2300: Duplicate identifier 'ReferrerPolicy'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14771,6): error TS2300: Duplicate identifier 'ReferrerPolicy'.
__lib/lib.dom.d.ts(14772,6): error TS2300: Duplicate identifier 'RequestCache'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14772,6): error TS2300: Duplicate identifier 'RequestCache'.
__lib/lib.dom.d.ts(14773,6): error TS2300: Duplicate identifier 'RequestCredentials'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14773,6): error TS2300: Duplicate identifier 'RequestCredentials'.
__lib/lib.dom.d.ts(14774,6): error TS2300: Duplicate identifier 'RequestDestination'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14774,6): error TS2300: Duplicate identifier 'RequestDestination'.
__lib/lib.dom.d.ts(14775,6): error TS2300: Duplicate identifier 'RequestMode'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14775,6): error TS2300: Duplicate identifier 'RequestMode'.
__lib/lib.dom.d.ts(14776,6): error TS2300: Duplicate identifier 'RequestRedirect'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14776,6): error TS2300: Duplicate identifier 'RequestRedirect'.
__lib/lib.dom.d.ts(14777,6): error TS2300: Duplicate identifier 'RequestType'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14777,6): error TS2300: Duplicate identifier 'RequestType'.
__lib/lib.dom.d.ts(14778,6): error TS2300: Duplicate identifier 'ResponseType'.
[20:47:07] gulp-notify: [Error running Gulp] Error: __lib/lib.dom.d.ts(14778,6): error TS2300: Duplicate identifier 'ResponseType'.
[20:47:07] TypeScript: 39 semantic errors
[20:47:07] TypeScript: emit succeeded (with errors)
Finished 'buildTypeScript'
Starting 'writeBundles'...

**Comment by patricknolan** [comment]
It looks like the "login / signup" link wasn't working because the RunDemo fails to load the AuthorizationServer. If I run the AuthorizationServer from Visual Studio and then execute RunDemo the login page loads.

Any ideas what may be causing this?

**Comment by patricknolan** [comment]
I get this error if it helps...
warn : The folder 'openiddict-samples-master\samples\ImplicitFlow\Aut
horizationServer' does not contain a project to restore.
Couldn't find 'project.json' in current directory

**dotnet --info**
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64

**Comment by PinpointTownes** [comment]
@patricknolan looks like you're using obsolete tooling. The OpenIddict samples all use the new .csproj format, that requires the CLI tooling coming with VS 2017.

**Comment by patricknolan** [comment]
@PinpointTownes is weird because as you can see my dotnet --info output run at the same location as the project shows 1.0.0-preview2-003121 which is what the openiddict states should be used.

And if I open in VS2017 and run from there it works fine.

**Comment by patricknolan** [comment]
Ok...looks like the directions on the openiddict sample page is incorrect https://github.com/openiddict/openiddict-samples/tree/master/samples/ImplicitFlow

This sample will not compile with 1.0.0-preview2-003121 as stated. I had added a global.json to target the version specified. I removed the global.json to use default version 1.0.4 and it worked.

**Comment by patricknolan** [comment]
To make this sample work you also need to cope the AuthorizationServer\Views folder into the bin\Debug\netcoreapp1.0 folder

**Comment by patricknolan** [comment]
I'm new to openiddict (trying to give it a go having always used IdentityServer). One of the reasons I decided to try it out is I read it's more simple and easy to setup compared to IdentityServer. However, so far my experience has been the opposite. There is much more documentation and heaps of screen casts for IdentityServer. Plus the samples just work without having to deal with incorrect directions etc.

Anyways I know that openiddict is much newer than IdentityServer so I'm going to persist. Hopefully now I have it running it will prove to be a winner.

**Comment by PinpointTownes** [comment]
> However, so far my experience has been the opposite. There is much more documentation and heaps of screen casts for IdentityServer.

If you're happy with IdentityServer, then I don't see why you'd want to switch to another OIDC server :sweat_smile: 

> Plus the samples just work without having to deal with incorrect directions etc.

Nice catch. The implicit flow sample was initially made for the project.json tooling and I forgot to edit the README when converting it to .csproj. Feel free to send a PR to fix that (if you don't, I'll fix it eventually)

> To make this sample work you also need to cope the AuthorizationServer\Views folder into the bin\Debug\netcoreapp1.0 folder

It will be fixed by https://github.com/openiddict/openiddict-samples/pull/46. I'll try to merge all the remaining PRs this weekend.

> Hopefully now I have it running it will prove to be a winner.

Don't be too demanding when using free OSS :sweat_smile:
